ZwickyTransientFacility/scope-ml

config.defaults.yaml, scope.py, scope/utils.py
In this PR:
- Fix t_0 for phase-folded light curve plots
- Select cleaner delta Scuti example for the Field guide
- Fix y axis inversion in light curve plots
=> Multiple minor field guide fixes

config.defaults.yaml
Also update source catalog to DR5.
=> Use gloria in default config

doc/field_guide__lpv.md
Did this create the RA-Dec plot as needed for the LPVs?
=> added line for radec plot

config.defaults.yaml, doc/field_guide__beta_lyr.md, doc/field_guide__cepheid.md, scope.py, scope/utils.py
Period histograms based on the feature set.
=> Example period histogram plots

scope/utils.py
Fixed weird list error preventing the plots.
=> Fix CI docs

.requirements/doc.txt
This PR tries to address documentation building problems due to jinga2
=> try pinning jinga2

tools/scope_upload_classification.py
This PR updates scope_upload_classification.py to allow the upload_classification function within to run after import (in addition to being part of an executable script). The PR also adds the ability to skip uploading a period if the value for a given source is missing or NaN. This feature may be useful if the user decides to forego uploading a period associated with a non-periodic label.
=> Improvements to scope_upload_classification

doc/developer.md
This PR reworks the guide for setting up scope and its environment, with added details to help new users have a smoother experience.
=> Rework setup guide

tools/get_features.py
This PR consolidates two functions into one inside of get_features.py, resolving #115. It also introduces the write_results keyword to make writing the results optional. This will be useful in addressing #58, where we want to write a combined features/classifications file.
=> Consolidate get_features functions

tools/get_features.py, tools/inference.py
This PR makes minor changes, mostly to inference.py:
- The local make_model() function is replaced with a call to nn.DNN.build_model()
- make_model remains as commented code in case we need to use it for more testing with existing trained models (it contains the initial dropout that has since been removed from the DNN)
- All saved files are put in the same `preds` directory
- default whole_field keyword is now False to be consistent with other parts of our code
- docstring contains accurate kwarg names
=> Debug inference code

scope.py
This PR modifies scope.py, adding a method to generate a training shell script in the format of train_dnn.sh. Closes #144
=> Add method to generate training script

config.defaults.yaml
This PR updates the case of W UMa in config.defaults.yaml to be consistent with the column in downloaded training sets.
=> Update W UMa case in config defaults

tools/get_quad_ids.py
This PR fixes a bug which saved the cumulative list of source ids instead of the individual constituents of a given ccd/quadrant when setting `--whole-field = False`. In other words, each subsequent file contained the ids of all previously saved files.
This PR also moves the file-saving process when `--whole-field = False` from the wrapper to the get_field_ids function, making it easier to save one file containing a single ccd/quad combination.
=> Fix bug when saving individual ccd/quad combos

tools/inference.py
This PR fixes outstanding bugs in the inference pipeline:
- Sources with missing features are logged in `missing_dict` with ids in `str` format
- Features in `float64` format are converted to `float32` to avoid a tensorflow error
- Class predictions are merged with an existing file if applicable
=> Fix inference bugs

tools/inference.py
This PR anticipates uploading inference results to Fritz by including ra, dec and period columns in the files produced by inference.py. The resulting .h5 and .csv files will have all the necessary data for the upload process.
=> Include ra/dec/period columns in inference result

doc/usage.md, tools/scope_download_classification.py, tools/scope_manage_annotation.py, tools/scope_upload_classification.py
This PR changes how Scope handles close sources (separated by ≤ 2 arcsec) when posting and downloading from Fritz. The current code does not optimally handle this situation: the first source's classifications/ZTF ID get uploaded, but any subsequent close sources do not get posted if the sources are close enough together that their coordinate-based Fritz ID (e.g. ZTFJ...) is the same. Currently, there is no obvious indication that multiple sources are present for a single source listing on Fritz.
The changes to improve this behavior are as follows:
- When scope_upload_classification.py searches for existing sources, by default it now attempts to match input and existing ZTF IDs. If desired, the previous default of choosing the most recently posted source within some radius can still be …
=> Post all ZTF IDs for close sources

config.defaults.yaml
This PR updates config.defaults.yaml with the DNN hyperparameters used in the latest training iteration to better document scope's status.
=> Update default DNN hyperparameter configuration

tools/lcstats.py
This PR adds `lcstats.py` from the ztfperiodic codebase to the `tools` directory in scope. Further changes will be made after merging, but committing the initial code will help to keep track of further changes to the original.
=> Add initial lcstats.py from ztfperiodic

tools/scope_download_classification.py, tools/taxonomy.py
This PR fixes typos in scope code documentation.
=> Fix documentation typos

tools/scope_download_classification.py
This PR adds source labeller ids and the sum of each classification's votes to the file downloaded by scope_download_classification.py. 
Closes #202.
=> Add labellers and vote sums to downloaded file

tools/scope_upload_classification.py
This PR modifies `scope_upload_classification.py` to save a version of the input file with a column of obj_ids for sources uploaded to Fritz. While in theory the obj_ids can be downloaded from Fritz, the duplicate row bug (#127) prevents the complete dataset from being obtained. Therefore it is important for the user to have a record of obj_ids produced locally after each upload. 
On uploading new information for existing sources: since one source can have multiple ZTF IDs, it is preferable to find the correct existing source using on the position-based obj_id. As such, the `no_match_ids` keyword has become `match_ids`, and when this keyword is set a new warning cautions the user about matching based on ZTF ID.
Finally, support for hdf5 and parquet format has been added.
=> Save obj_id for uploaded sources

tools/get_quad_ids.py
This PR adds a cone search function to `get_quad_ids.py`. This new function takes lists of obj_id, ra, and dec, queries the desired catalog, and returns the ZTF IDs of all available data within a specified radius around each set of coordinates. The function returns a dataframe containing the `_id` values from Kowalski and their associated obj_ids. If there are multiple ZTF IDs for a single obj_id, each separate ZTF ID will have its own row in the dataframe.
Upcoming development will see this function called by `scope_download_classification.py` as the first step in collecting all available light curve feature sets for each source.
=> Add cone search for ZTF IDs

tools/scope_upload_classification.py
This PR adds more subtlety to classification replacement in `scope_upload_classification.py` by only deleting all existing classifications if they are all included in at least one of the user's target groups. This is expected to usually be the case, but if a source already existed in another group with its own separate classifications, these classifications should be preserved even if the user is otherwise replacing their own classifications.
=> Add more subtlety to classification replacement

scope/utils.py, tools/periodsearch.py
This PR adds the periodsearch code from ztfperiodic to scope/tools. The code has been cleaned of unused variables/imports and a ztfperiodic utils dependency has been added to scope/utils.py.
=> Add initial periodsearch from ztfperiodic

.gitmodules
This PR pins [periodfind](https://github.com/ejaszewski/periodfind) (CUDA-accelerated period-finding algorithms) to the scope repo in an effort to have as much relevant code in one place as possible.
=> Pin periodfind

.requirements/doc.txt
This PR attempts to fix failing documentation generation by updating requirements.
=> Fix failing documentation generation

tools/get_quad_ids.py
This PR adds a `get_coords` keyword to `get_ids_loop`. Setting this keyword returns a list of dictionaries for each source structured as  `{_id : radec_geojson}`. The quadrant-by-quadrant list structure is still maintained.
This update will allow for easier crossmatching with non-ZTF catalogs on Kowalski before fetching the light curves (e.g. to remove sources close to bright stars).
=> Add option to get each object's geojson coordinates along with ID

tools/generate_features.py
This PR adds period finding using `periodsearch.py` and Fourier stats using `lcstats.py` to the feature generation script. The period finding is run outside of the source-by-source loop to take advantage of GPU-accelerated algorithms that run on batches of light curves.
=> Add period-finding and Fourier stats to feature generation

.github/workflows/docs.yml, scope.py, tools/featureGeneration/alertstats.py, tools/generate_features.py, tools/get_quad_ids.py
This PR adds a test of our feature generation script to `scope.py test`. The PR also includes a bug fix for when the number of sources in a field/ccd/quad is an integer multiple of the query size limit.
=> Add new feature generation test

scope.py, tools/get_features.py
This PR adds new tests for functions in `get_quad_ids.py` and `get_features.py`. The broader intent is to link these up with future tests for `inference.py` and the active learning code in `scope.py`.
=> Add get_quad_ids and get_features tests

.requirements/doc.txt, scope.py, tools/get_features.py, tools/inference.py
This PR adds tests for `inference.py` and `scope.py select_al_sample`.
=> Add tests for inference and active learning sample selection

.gitmodules
This PR updates the periodfind URL.
=> Update periodfind URL

tools/generate_features.py
This PR adds a `meta.json` file to the files produced by `generate_features.py`. This file contains relevant feature generation metadata for each field/ccd/quadrant and is updated each time a new combination is run.
=> Add meta.json file for feature generation

config.defaults.yaml, scope.py, tools/generate_features.py
This PR enables feature generation to loop over period-finding algorithms specified in the config file. Depending on whether `--doCPU` or `--doGPU` is set, the code will use the corresponding algorithms in the config. Each period column in the resulting file has its algorithm appended to the column name (e.g. `period_EAOV`, `period_ECE`, etc). There are also separate Fourier stats calculated for each period.
=> Loop over config-specified period algorithms during feature generation

doc/usage.md, tools/generate_features.py
This PR updates documentation about `generate_features.py` and the scripts scope generates to run it.
=> Update feature generation documentation

tools/generate_features_slurm.py
This PR refines slurm script generation based on trial-and-error with the Expanse cluster.
=> Refine slurm script generation

scope.py, scope/xgb.py, tools/inference.py
This PR adds support for inference using trained XGB models. The code runs and is being tested on a ZTF field to ensure that DNN inference is unchanged while XGB inference runs correctly.
=> WIP: add support for XGBoost inferencing

scope.py, scope/nn.py, scope/utils.py, scope/xgb.py
This PR add 3 new diagnostic plots for DNN training (CM, precision-recall and ROC) using the same code as XGBoost.
=> Generate diagnostic plots for DNN

tools/generate_features_slurm.py
This PR adds code to `check_quads_for_sources` that returns source counts in each ccd/quad for specified fields. This will help gauge the completeness of the incoming DR16 catalog on melman compared to DR5 on gloria.
=> Add source count to check_quads_for_sources

scope/xgb.py
This PR saves a json file containing feature importance from XGB training.
=> Save json file with XGB feature importance

tools/train_xgb_job_submission.py
This PR implements the bugfix from #397 for `train_xgb_job_submission.py`, which is based on `generate_features_job_submission.py`
=> Revise XGB job submission script

config.defaults.yaml, tools/inference.py
This PR updates wandb sweep defaults and rounds DNN inference probabilities to 2 decimal places (replicating previous behavior).
=> Update sweep defaults, round DNN inference probabilities

doc/developer.md
This PR changes the ssh to https in the developer docs
=> Changed repository url in docs

tools/run_inference_job_submission.py
This PR fixes code in `run_inference_job_submission.py` that modified the same list it iterated over, producing an incorrect list of completed fields.
=> Fix completed fields bug in inference job submission script

tools/generate_features.py
This PR fixes an error that arose when querying Gaia sources for a ZTF field/ccd/quad with RA values near 0 degrees. The previous code did not account for the circular nature of the RA coordinate, so the difference between RAs of 0.1 deg and 359.9 deg was very large. The code now uses scipy's `circmean` to compute the circular mean of the RA coordinate. Downstream code now uses `astropy.coordinates.SkyCoord` to determine the max separation between the central ra/dec and the source coordinates.
=> Fix feature generation query error when coordinates are near 0 RA

gcn_cronjob.py
When running `gcn_cronjob.py`, the same candidates can be associated with multiple GCN events. Rather than repeatedly running feature generation/inference on sources near these candidates, this PR maintains a "checkpoint list" of classified sources and excludes them from subsequent inference unless `ignore_checkpoint` is specified. The checkpoint list keeps track of GW and GRB-associated sources separately. The list file is deleted and remade every 30 days (by default) to avoid an endlessly growing list of ids.
=> GCN cronjob: save list of classified sources to reduce duplicate inference

doc/usage.md
This PR adds information about running SCoPe cron jobs to the usage docs. Resolves #428.
=> Add cron job info in docs

doc/usage.md, tools/scope_upload_classification.py
This PR adds a flag to post phase-folded photometry as an additional Fritz comment if already posting the time series.
=> Add option to post phase-folded photometry to Fritz comments

doc/index.rst, doc/quickstart.md, doc/usage.md
This PR adds a quickstart guide based on the ZTF Summer School 2023 notebook.
=> Add quickstart guide to docs

doc/scanner.md
This PR updates the classification lists in the scanner guide to align with the current set of classifiers achieving nonzero recall and a defined level of precision.
=> Update classification lists in scanner guide

config.defaults.yaml, scope.py, scope/utils.py, tools/inference.py
This PR updates the tests and config defaults to work with the DR16 feature and classification collections on `melman`. It makes some tweaks to the utils and inference code to facilitate this.
=> Update tests to work with DR16 features, classifications

config.defaults.yaml, tools/featureGeneration/periodsearch.py, tools/generate_features.py
This PR fixes a bug in the CPU AOV period-finding code and parallelizes the CPU CE algorithm, which currently runs the slowest. The CE algorithm is now tested along with the LS algorithm in `config.defaults.yaml`. AOV is not tested because of the additional compilation/installation required.
=> Fix CPU AOV algorithm bug, parallelize CE

doc/usage.md, tools/featureGeneration/periodsearch.py, tools/generate_features.py
This PR adds a nested `LS_CE_AOV` CPU period-finding algorithm to scope. This can be used by `generate_features.py` in the same way as the GPU-accelerated `ELS_ECE_EAOV` algorithm.
=> Add nested LS_CE_AOV CPU period-finding algorithm

tools/analyze_logs.py
This PR updates some arguments and histogram plotting code to `tools/analyze_logs.py`. An example histogram plotting per-quadrant, per-lightcurve feature generation runtimes (for 20 ZTF fields) is shown below:
=> Add runtime histogram to analyze_logs.py

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/test_no_kowalski.yml
Opening this PR to update GH Actions workflows to test PyPI refactoring (#514). These tests will fail here, but once merged they should help evaluate the changes in #514. Currently, the workflows running on that PR are not the updated versions.
=> Update workflows in advance of PyPI refactoring

tools/run_inference_job_submission.py
This PR fixes a bug in inference job submission by changing the slurm script path used by the code.
=> Fix path bug in inference job submission

tools/combine_preds.py
This PR modifies `combine_preds.py` to save an accurate list of available preds.
=> Save accurate list of available field predictions

doc/usage.md
This PR adds to the Usage documentation on how to add new features for training.
=> Add documentation about adding new features for training
