ZwickyTransientFacility/scope-ml

- .requirements/dev.txt
- scope/nn.py
Randomly dropping input feature/dmdt data is a bad idea and I'm not sure why I had it there in the first place. My guess is that the DNN performance will significantly improve once that is removed.
> Do not use Dropout for input features/dmdt's

- scope/fritz.py
Make new user experience easier by hard-coding https protocol and Fritz URL.
> Hard-code fritz.science URL

- doc/developer.md
- doc/usage.md
- tools/scope_upload_classification.py
Added ability to upload no classification to Fritz, since duplicates easily arise (especially during testing). Also removed sys.path.append() in favor of adding scope directory to PYTHONPATH locally (now described in documentation). Other typo corrections in usage instructions.
> Improve source uploading and documentation

- doc/usage.md
- tools/scope_upload_classification.py
This PR adds the functionality for scope_upload_classification.py to upload multiple classifications to Fritz at once. In this mode of use, the mapping of source dataset labels to Fritz taxonomy is provided by the user as a JSON file. The code checks existing classifications to avoid uploading duplicates. There is also a new option to upload a comment for each source in the input file. usage.md has been updated to reflect this new functionality.
> Add multiple-classification uploads

- doc/usage.md
- tools/scope_manage_annotation.py
This PR adds a new tool (scope_manage_annotation.py) that manages Fritz annotations. The tool takes either one source or a CSV file of many, and for each one posts, revises, or deletes a specified annotation. The script performs several checks on the inputs and communicates the status of each run.
> Script to manage annotations

- doc/usage.md
- tools/scope_download_classification.py
This PR improves the scope_download_classification.py tool. The user can provide a CSV file of object ids and/or ra-dec coordinates to query sources. There is also a "parse" option that queries all sources in a given group(s) without requiring an input file. In each case, the script creates a new CSV file containing each source's classifications, probabilities, and period annotations. The format of the classification column matches the output obtained from a download using the Fritz interface.
> Improve classification downloads

- doc/usage.md
- tools/scope_download_classification.py
This PR speeds up group source downloads by eliminating unneeded API calls. If -file is set to 'parse', a download of ~2500 sources completes in ~3 minutes. There remains the option to download specific sources, but this process still loops over each source and takes longer. The new code also adds checkpoints to save results periodically and allows intermediate resumption in the case of an interrupted download.
> Increase group source download speed

- doc/usage.md
- scope/fritz.py
- tools/scope_upload_classification.py
This PR enables multiple classifications to be uploaded together to Fritz. Classifications are uploaded in a batch with size specified by UPLOAD_BATCHSIZE
Other minor changes:
- option to skip photometry search/upload for existing sources to save time
- use of config.yaml to provide Kowalski authentication, instead of requiring secrets.json
- repositioning of the taxonomy map read-in to avoid doing it multiple times
- use of the RADIUS_ARCSEC variable to provide the radius for coordinate searches
> Enable multiple classification uploads

- tools/taxonomy.py
This PR modifies taxonomy.py to facilitate taxonomy uploads to Fritz. Users can now import a taxonomy module (e.g. [scope-phenomenology](https://github.com/bfhealy/scope-phenomenology) in python, pass in the module into taxonomy.py, and upload it. The original functionality requiring a path to a YAML file remains as another option, although users must now also specify a name, version and provenance.
> Overhaul taxonomy upload script

- scope/fritz.py
- tools/golden_dataset_mapper.json
- tools/scope_upload_classification.py
This PR enables classifications spanning multiple taxonomies to be uploaded to Fritz. golden_dataset_mapper.json, which contains the mapping from dataset labels to Fritz classifications that gets passed into scope_upload_classification.py, is included as a new file in tools. This file also contains the taxonomy ids connected to each classification. Finally, since photometry uploaded to Fritz via the PUT request does not get duplicated, code comparing existing and new photometry in fritz.py has been removed to make uploads run faster.
> Enable classifications from multiple taxonomies

- scope/fritz.py
- tools/golden_dataset_mapper.json
- tools/scope_upload_classification.py
This PR fixes bugs relating to batch uploads of classifications:
- The list of classifications is now reset after each upload, preventing duplicate uploads
- The start/stop arguments can now be used independently
- UPLOAD_BATCHSIZE is limited to 10 by default instead of 100 (timeout)
- Batch uploads count up to UPLOAD_BATCHSIZE correctly regardless of start index
- An error is raised if MAX_ATTEMPTS is reached for batch uploads
> Fix batch upload bugs and typos

- tools/scope_upload_classification.py
The start and stop indices for a dataset are now always assigned in scope_upload_classification.py, even if not specified by the user. Both variables are used later in the script during the batch upload. This PR also fixes a bug in which the final batch of labels does not upload if the batch size is smaller than UPLOAD_BATCHSIZE.
> Always assign start/stop, upload last batch

- scope/fritz.py
- tools/scope_upload_classification.py
This PR 'protects' an api call in fritz.py (added in #101) which previously lacked a try/except loop for connection errors (see #86). The PR also adds new connection-related error (JSONDecodeError) to check in fritz.py and scope_upload_classification.py.
> Additional connection try/except

- scope/utils.py
This PR flips the sign of a magnitude difference to avoid negative `yerr` values.
> Flip sign of magnitude difference

- tools/scope_manage_annotation.py
This PR makes scope_manage_annotation.py more robust to different datatypes. If a CSV file is passed in, the annotation column's datatype will be converted from a numpy to python dtype to avoid an error on posting. If a single source and key/value pair is instead specified, the value (initially a str) will be converted to a float or int as appropriate. The script also now loops over all keys under a given origin to check for matches, rather than selecting a single key.
> Handle multiple annotation datatypes

- doc/usage.md
- scope/fritz.py
- tools/scope_upload_classification.py
This PR revises source uploads by:
- Removing unneeded try/except loops (thanks to #111)
- Adding an optional upload of each source's ZTF id as an annotation
- Selecting the most recently posted source whose id begins with 'ZTFJ' as the existing source (if applicable). Previously, if multiple nearby sources existed, the script would effectively select one at random.
- Updating the usage documentation
fritz.py also has a one-line change to api(): the call to sleep() now takes place after an exception is caught. This change speeds up api calls that do not produce an error.
> Revise uploads and increase speed

- tools/get_features.py
This PR fixes a bug that threw an error when using the `get_field_features` function within get_features.py. The criterion to break the loop has been modified so it doesn't fail when the length of the input list of source ids is an integer multiple of the per-query limit. Both get_features functions also now return their main outputs.
> Fix loop bug in get_field_features

- doc/usage.md
- tools/get_features.py
- tools/scope_download_classification.py
This PR incorporates the get_features.py code into scope_download_classification.py to query and download features from Kowalski before merging them with a source list from Fritz, either downloaded or provided as input (closes #58). The merge is done by matching ZTF id numbers after checking that both tables come from the same data release. 
All files produced by scope_download_classification are now saved in a directory called 'fritzDownload' within scope/tools. Previously they were saved in the tools directory.
My tests of the the code produce the same form of file as the initial golden dataset, with minor differences in columns. The newly produced dataset has an additional column called 'coordinates' from the features database, and it is missing the 'nice' and 'niice' classification …
> Enable source/feature merging

- doc/usage.md
This PR adds the link to a new google drive folder containing trained models.
> Add google drive link to trained models

- tools/scope_download_classification.py
This PR modifies the feature-merging part of scope_download_classification.py to handle classifications that are not in the input dataset label mapper. This issue arises, for example, when a source already existed on Fritz with classifications from a separate taxonomy prior to the user's upload of that source. The new code skips over classifications that are missing from the mapper, which the user can modify if the additional classifications are of interest.
> Handle unrecognized classifications when merging features

- config.defaults.yaml
This PR updates the training section of config.defaults.yaml to include all phenomenological and ontological classes that are present in the golden dataset. While some classes do not currently have enough examples to effectively train the DNN, it is helpful to have a complete list in the config file.
> Add all phenomenological/ontological classes to config.defaults.yaml training section

- tools/golden_dataset_mapper.json
The original golden dataset had a column labeled 'elliptical' which after inspection appears to describe ellipsoidal variables. The mapper between the dataset and Fritz previously contained the original column name, but with the dataset now uploaded to Fritz we can correct the column name in this PR. Future downloads from Fritz will produce an 'ellipsoidal' column.
> Fix ellipsoidal label in mapper

- scope/__init__.py
This PR adds versioning to `scope/__init__.py` based on code adapted from [this file](https://github.com/skyportal/skyportal/blob/main/skyportal/__init__.py) in SkyPortal. I think a logical initial version is 0.2.dev0, recognizing development since the initiation of the project. The current git commit hash is also included for further version detail.
The broader goal is to include the code version in a header attached to downloaded training sets (#130).
> Add versioning

- doc/usage.md
- tools/get_features.py
- tools/get_quad_ids.py
- tools/inference.py
- tools/scope_download_classification.py
This PR saves features from Kowalski in parquet format instead of pickle, optimizing disk space. Metadata for the feature download is now generated within get_features.py rather than scope_download_classification.py. The parquet file is also supported as an input to inference.py.
During my testing of this new code, I removed a remaining relative filepath in get_quad_ids.py. I also tweaked the documentation for running get_features.py.
> Write features as parquet file

- scope.py
- scope/utils.py
This PR enables .parquet and .h5 files to be read by the `Dataset` class, which is used during training.
> Add Parquet, HDF5 support to Dataset class

- scope/fritz.py
This PR adds the `group_ids` keyword to the photometry JSON object that gets uploaded to Fritz. This change will allow photometry to be seen by members of the groups specified by this keyword.
> Add group_ids to photometry json

- doc/usage.md
- scope.py
This PR allows custom keywords to be appended in bulk to the training script generated using `./scope.py create_training_script`. The usage documentation is also updated to mention this method.
> Add custom keywords to training script

- tools/get_features.py
This PR adds a keyword controlling the writing of features as a CSV file, making it optional (and `False` by default) to save disk space. Features continue to be written in .parquet format by default.
> Make CSV optional in get_features

- tools/inference.py
This PR fixes a bug when performing inference using a .parquet features file. Unlike the previous pickle format, loading the parquet file changes python lists to numpy arrays. This raised a tensorflow error when passing dmdt into model.predict().
> Fix dmdt inference bug

- tools/get_features.py
- tools/scope_download_classification.py
This PR refactors get_features.py to enable checkpoint saving for large feature downloads. For fields with millions of sources, the feature downloads often freeze and fail. This new code (mainly the `get_features_loop` wrapper) writes features to a parquet file (CSV optional) for every 100,000 sources by default. If the download is cut off, the user can re-run the same code to continue downloading from the last checkpoint.
The existing use of get_features.py code in scope_download_classification.py is tested and adjusted to continue working properly.
> Checkpoint feature downloads

- README.md
This PR updates README.md to include how to generate local HTML documentation since scope.ztf.dev is down.
> Add readme instruction for generating docs locally

- tools/get_features.py
This PR modifies get_features.py to save multiple feature files per field, quantified by a default number of sources (100,000). It removes the prior functionality that updated existing files - reading and appending to increasingly larger files for populous fields becomes very memory-intensive.
The Parquet format supports datasets spread across multiple files (see e.g. https://arrow.apache.org/docs/python/dataset.html#dataset). Going forward, we will be able to perform inference on these file collections using a simple loop to preserve memory.
> Save multiple feature files per field

- tools/inference.py
This PR modifies inference.py to loop over the contents of multiple parquet files containing a field's features. The new code requires much less memory without a major increase in inference time.
> Loop over multiple parquet feature files during inference

- config.defaults.yaml
- scope.py
- tools/inference.py
This PR continues the debug/improvement process for the inference pipeline. It modifies config.defaults.yaml, restructuring the phenomenological and ontological feature lists. Each feature on the list now has a boolean `include` field (taking the place of the `#` used in the previous version). This PR would supersede #142, so features having `include = True` are the same as agreed upon in that discussion.
Each feature in the config file also has a `dtype` field to explicitly specify the datatype. An upcoming PR will make use of this field to ensure more consistency in files generated by `get_features.py`. Currently, pandas does not always infer types uniformly.
Lines in `scope.py` and `inference.py` where the config features list is used are refactored in this PR for compatibility with …
> Restructure features lists in config defaults

- tools/get_features.py
Following up on #164, this PR modifies get_features.py to set feature datatypes based on the contents of the scope config file, ensuring consistency among each parquet file saved for the field.
This PR also updates how interrupted downloads are resumed given the use of many parquet files to comprise a field's dataset. As long as DEFAULT_SAVE_BATCHSIZE is kept constant for the field, an interrupted download can be resumed by running the same command again.
> Set feature datatypes and resume interrupted downloads

- config.defaults.yaml
- scope/__init__.py
- tools/inference.py
This PR saves inference results in HDF5 format including relevant metadata. CSV files can optionally be saved as well.
Also, the datatype of the `_id` field is changed from pandas `Int64` to `int` to avoid an error when saving inference results. Finally, the version of the code is bumped.
Closes #160
> Save inference results in HDF5 format

- doc/usage.md
- tools/scope_upload_classification.py
This PR adds a probability threshold argument to scope_upload_classification.py. Only classifications with a probability greater than the threshold will be uploaded. This is useful for active learning purposes and any time we want to post only a subset of potential classifications.
> Add probability threshold for classification uploads

- tools/scope_upload_classification.py
This PR ensures that a source's ZTF ID is converted to an integer before its string representation is uploaded to Fritz.
> Convert ZTF ID to int before uploading

- tools/scope_upload_classification.py
This PR fixes a bug in scope_upload_classification.py where an error is raised during annotation posting if a source exists on Fritz but without any ZTF ID annotation. The code now handles this scenario by posting a new annotation to Fritz in the same way that it would if the source did not exist.
> Fix annotation bug for existing sources with no ZTF ID

- config.defaults.yaml
- scope/fritz.py
- tools/scope_upload_classification.py
This PR reorganizes and updates the default values for the try/except loop governing Fritz API calls. The defaults of 10 attempts and 5 seconds between attempts are defined at the top of fritz.py, and one extraneous default value is removed from scope_upload_classification.py
> Reorganize and update defaults for API try/except loop

- doc/usage.md
- tools/scope_download_classification.py
This PR revises `scope_download_classification.py`, renaming the `mapper_name` argument to `taxonomy_map`. This revision achieves consistency with the identical argument in `scope_upload_classification.py`. The documentation in `usage.md` is also updated with a new section describing how to create taxonomy map files. This PR is separate from #182 because it involves more than just a documentation update.
> Standardize taxonomy map keywords, add documentation

- tools/DNN_AL_mapper.json
Uploading DNN classifications to Fritz for active learning requires a JSON file to map the column names of inference results to Fritz taxonomy labels. This PR adds the current mapper for DNN active learning to the scope repository.
> Add DNN active learning mapper

- tools/inference.py
This PR fixes an issue where `model.predict` freezes mid-inference. The issue likely arises due to a memory leak (e.g. [here](https://github.com/keras-team/keras/issues/13118) and [here](https://github.com/tensorflow/tensorflow/issues/44711)) as our code loops over feature files. Among many proposed solutions, the one I've found to make the most difference is replacing `model.predict(features)` with `model(features, training=False)`. This replicates the output of the original code with negligible difference in speed, but prevents ballooning memory to the point of freezing.
> Replace model.predict in inference loop to avoid memory leak

- scope.py
This PR adds a `select_al_sample` method to `scope.py` to select sources and their classifications from a collection of predictions and make an active learning sample. The method optionally removes sources in the current training set before selecting at random a user-specified minimum number of sources having classifications with probabilities ≥ a given probability threshold. The output is a dataset that can be posted to Fritz using `scope_upload_classification.py`. 
One additional feature to consider is a fixed random state to allow reproducible active learning samples to be made from the same collection of predictions.
> Add method to select sources/classifications for active learning

- .requirements/dev.txt
- scope.py
- scope/nn.py
This PR fixes an error that was raised when running additional training on pre-trained models. The callbacks metadata for the pre-trained model is not saved and so cannot be loaded in like the rest of the model components. Thus, there is now a separate `set_callbacks` method in `nn.py` which is called when loading in a pre-trained model. 
Additionally, this PR adds compatibility with the latest `tensorflow-macos` (2.11), which raises an error when accessing `tf.keras.optimizers.Adam`. The replacement, `tf.keras.optimizers.legacy.Adam`, is also included in the previous `tensorflow-macos` version (2.10), so this change will not break scope on environments set up in September 2022 and onward.
(On the topic of tensorflow versions and M1 Macs, see also the updates in #125 pertaining to GPU …
> Fix callbacks for pre-trained model, use legacy optimizer

- scope/fritz.py
- tools/scope_upload_classification.py
This PR reorganizes source uploads to skip sources without photometry. If a list of uploaded sources is requested, sources without photometry will have an empty field in the obj_id column to indicate that they were not uploaded.
> Handle missing photometry during source upload

- tools/get_features.py
This PR updates `get_features.py` to allow more flexibility when retrieving features. The user can now specify a projection for a Kowalski query that restricts the columns returned. When `get_features.py` is called from the command line, this projection is generated from the `column_list` argument, which contains the list of features desired by the user. Furthermore, the new `features_catalog` argument allows the user to specify which catalog to query without editing the code.
The motivation for this change is the lack of ZTF filter ids in the current Scope feature collection (`ZTF_source_features_DR5`). This information may be relevant for upcoming training, so it is important to have a quick way to query a different catalog (`ZTF_sources_20210401`) for a single column (`filter`).
> Add more flexibility to get_features.py

- tools/scope_upload_classification.py
This PR moves the code that uploads batch classifications, allowing the batch to be posted even if the last source of the batch did not get uploaded.
> Always upload batch classifications

- doc/usage.md
- tools/get_features.py
- tools/scope_download_classification.py
This PR primarily reworks `scope_download_classification.py` to download all available sets of features for each source on Fritz. Since multiple ZTF ids can be associated with a single source (corresponding to different light curve bands/fields), the one-to-one ZTF ID matching previously performed in this code has been removed. The new code uses the coordinate-based object ids from Fritz to connect labels and features.
A cone search finds all available feature sets within 2 arcsec (default) of the input coordinates for each Fritz source. In cases where multiple sources 'claim' a feature set, the source having the smallest Euclidean distance from the feature coordinates is assigned the set.
The ZTF filter ID for each feature set, which is currently located in a separate catalog, can be …
> Download all available feature sets

- tools/scope_upload_classification.py
Some sources on Fritz have IDs that use the same ZTFJ... format we use for Scope's position-based identifiers, but they are posted to other groups for separate purposes. When using the `-skip_phot` flag (e.g. to update classifications without posting new photometry), these sources are quietly added to our specific groups, even if they lack any unflagged ZTF photometry points.
This PR adds an additional check on these sources to avoid the above scenario. If an existing source is not posted to all of the groups specified by the user in their call to `scope_upload_classificiation.py`, the code will treat the object as a new source and pass it through the necessary photometry checks.
> Additional check on existing sources' group membership

- tools/scope_download_classification.py
This PR passes the `get_ztf_filters` flag to the feature download code in `scope_download_classification.py` when the script's arguments include an input file from Fritz. The flag was previously missing from the function call.
> Get ZTF filters when starting with Fritz downloaded file

- doc/usage.md
- tools/scope_upload_classification.py
This PR allows the user to delete/replace each source's existing classifications when uploading new classifications. This will be useful for active learning purposes as we replace outdated classifications from a previous round of training.
> Add option to delete existing classifications during upload

- scope.py
- scope/utils.py
This PR updates the training pipeline in two ways:
- Any `numpy.float64` columns in the features datafame are converted to `numpy.float32` to be compatible with Tensorflow. This behavior is customizable with the `float_convert_types` argument.
- Feature stats are no longer sourced from the values in the config file by default. Instead, they are computed after imputation by a new function in `utils.py`. Setting `feature_stats = "config"` will produce the old default behavior.
> Update training pipeline

- scope.py
- tools/inference.py
This PR updates the inference pipeline as follows:
- Features are self-imputed based on each batch of sources (see #233).
- The sequence of imputation -> feature stats -> scaling is now the same as the training process.
- Feature stats are by default generated with the new function in `utils.py` (see #232). The stats are generated from the training set to ensure scaling consistency between training and inference.
- The `create_inference_script` method has a new argument allowing the user to specify the feature scaling method.
> Inference updates

- scope.py
- tools/inference.py
This PR adds code to consolidate inference results such that there is only one row per source. The code supports taking the mean, median or max of multiple classification probabilities to compute the consolidated value. Unique sources are identified using each row's associated Gaia EDR3, AllWISE or Pan-STARRS ID (in that order). In addition to the AL subset which gets produced, the new code can also save the full list of all rows and the full consolidated source list.
> Consolidate inference results

- tools/DNN_AL_mapper.json
This PR updates the mapper for local active learning classifications and the latest Fritz taxonomy IDs.
> Update active learning mapper with new taxonomy IDs

- scope.py
This PR updates the active learning pipeline in several ways. The primary update is to add a new method of selecting the AL subset from the multi-field consolidated sample. Since some classifications do not have any examples with probabilities above a certain high-confidence value (e.g. 0.9), this new method instead selects the top N sources for each class. The user can still specify the `probability_threshold` below which classifications are ignored, but the threshold can now be reduced and still yield only the most confident sources for each class. This new functionality can be called by setting the `--select_top_n` keyword in the call to `select_al_sample`.
There is also the option, enabled by setting `--include_all_highprob_labels`, to include all classifications above …
> Update active learning pipeline

- tools/scope_upload_classification.py
This PR allows the replacement of classifications belonging to no groups on Fritz. Currently `scope_upload_classification.py` will not identify a classification for deletion if its `groups` field is empty. In the case that sources in our current active learning group on Fritz overlap with our new sample and need their classifications replaced, this change will prevent the old classifications from remaining along with the new ones.
> Allow classifications belonging to no groups to be replaced

- doc/usage.md
- tools/scope_download_classification.py
This PR adds the option to impute missing features in `scope_download_classification.py`. It also fixes a bug that was assigning the wrong ZTF filter IDs to downloaded sources. This bug has not affected current active learning efforts.
> Add feature imputation to downloads and fix filter bug

- tools/scope_upload_classification.py
This PR extends the functionality of the `-check_labelled_box` keyword in `scope_upload_classification.py` to classification deletion when `-replace_classifications` is set. This fixes an issue where sources would be checked as labelled if their classifications were replaced by the upload script.
(Anticipates deploy of the related SkyPortal change to Fritz)
> Make checkbox optional when deleting classifications

- config.defaults.yaml
- tools/golden_dataset_mapper.json
All training sources on Fritz having the `galaxy` label now also have the `extended` label from the latest SCoPe Phenomenological Taxonomy. Thus, this PR renames `galaxy` to `extended` in both the golden dataset label mapper and the default config file. In the config file, two other classes with few positive examples also have a new `batch_size` argument in their hyperparameter info.
> Rename galaxy to extended in golden dataset mapper

- tools/get_quad_ids.py
This PR allows the `get_field_ids` function within `get_quad_ids.py` to return ids for `ZTF_sources_...` catalogs, which do not contain the `n` entry created during feature generation. The `{"n" : {"$gt": minobs}}` filter parameter is now only included if `minobs` is nonzero. `get_field_ids` can now be used at the start of the feature generation process in addition to the inference process.
> Skip Kowalski filtering by n points if minobs is zero

- tools/get_quad_ids.py
This PR makes saving optional in `get_ids_loop`. The default remains to save the ids. The code now also prints the total number of IDs found.
> Make saving ids optional in get_ids_loop

- .requirements/doc.txt
- doc/usage.md
- tools/periodsearch.py
- tools/pyaov/aov.f90
- tools/pyaov/aovconst.f90
- tools/pyaov/aovsub.f90
- tools/pyaov/build.sh
This PR adds the package and code requirements to run the CPU-based `LS`, `CE` and `AOV` period-finding algorithms in `periodsearch.py`. `AOV_cython` is not yet supported. The usage documentation also has a new section describing the in-progress work to bring feature generation to scope, along with the specific instructions to get the `AOV` algorithm working.
> Update code/package requirements for CPU period algorithms

- tools/get_quad_ids.py
This PR modifies `get_ids_loop` in `get_quad_ids.py` to return an additional variable containing a list of each CCD/quadrant's ZTF IDs. The list is organized such that each element contains all the IDs for one CDD/quadrant pair.
> Return organized list of ccd/quadrant ids

- scope/utils.py
This PR adds a function to `scope/utils.py` to remove all but the first high-cadence data points from a light curve.
> Add util to remove high-cadence data

- scope/utils.py
This PR adds utils to:
- Convert Gaia $G < 13$ and $BP-RP$ magnitudes to Tycho $B$ and $V$
- Calculate the radius within which to exclude sources near bright stars (as a function of $B$ and $V$).
> Add bright star exclusion radius utils

- scope/fritz.py
- tools/get_quad_ids.py
This PR renames the `gloria` variable to `kowalski_instance` in `get_quad_ids.py` and `fritz.py`. For functions in `get_quad_ids.py`, the instance can also now be passed in as an argument. These changes assist upcoming feature generation code, which requires querying multiple instances of Kowalski machines.
> Rename gloria to kowalski_instance

- config.defaults.yaml
This PR adds a Kowalski timeout to the config file and updates source/feature collections to the most recent available versions.
> Add Kowalski timeout to config, update collections

- tools/get_quad_ids.py
This PR allows ints to be passed to the `ccd_range` and `quad_range` parameters in `get_ids_loop`. Previously a list of two ints had to be passed in even if the user only wanted one ccd/quadrant done.
> Allow single ccd/quad to be passed into get_ids_loop

- scope/__init__.py
- tools/generate_features.py
This PR adds a preliminary script in `tools/generate_features.py` to generate features from ZTF light curves. Upon running `./generate_features.py`, the script performs the following:
- Get IDs/coords for a field/ccd/quad combo
- Query Gaia for nearby sources brighter than G=13 (default 300 arcsec radius, ~the largest exclusion radius of A. Drake's findings)
- Calculate exclusion radii and drop sources too close to a bright star
- Get light curves for remaining sources
- Drop all flagged light curve points
- Drop all but the first point from groups of high-cadence data (default 30 min)
- Apply a threshold for minimum number of points (default 50) after the above cuts
- Compute 'features': currently a few test statistics (to be replaced by lcstats, periodfind etc.)
- Write results in …
> Add feature generation script

- config.defaults.yaml
- tools/featureGeneration/alertstats.py
- tools/generate_features.py
This PR adds code to get the `n_ztf_alerts` and `mean_ztf_alert_braai` features from the `ZTF_alerts` catalog on `kowalski`. The new code in `tools/featureGeneration/alertstats.py` is called by `generate_features.py`.
Since my `kowalski` token is different than the one that covers `gloria` and `melman`, I added an `alt_token:` field in `config.defaults.yaml` to allow me to authenticate a `kowalski` instance for the alerts. In this file there is also a new `alerts` field that allows the user to specify the name of the alerts collection.
> Get ZTF alert stats

- tools/generate_features.py
This PR adds basic light curve stats to `generate_features.py` by calling `lcstats.calc_basic_stats()`. It replaces the placeholder light curve features in #271.
> Add basic light curve stats to feature generation

- scope.py
This PR fixes the failing doc tests seen after today's PRs have been merged. The source of the failures is the updated config-default source catalog (ZTF DR15, `ZTF_sources_20230109`), which is only available on `melman.caltech.edu`. Since `gloria` is still relied upon for many scripts in scope, it would be disruptive to change the default host to `melman`. Instead, this PR comments out the line providing the config-default catalog in `scope.py doc`. The code now defaults to the `ZTF_sources_20210401` (DR5) specified in the `catalog` argument for `_get_light_curve_data()`.
In the future, hopefully this line can be uncommented and a `KowalskiInstances` class will manage the various instances more seamlessly.
> Fix failing doc tests

- .github/workflows/docs.yml
The new tests are passing except for a failed docs deployment. The docs workflow should not even be attempting to deploy until a PR is merged, so something is not working as it used to. This PR changes the condition for deploying docs within Github Actions.
I think the change from `pull_request` to `pull_request_target` sets `github.ref` to `'refs/head/main'` even within a PR branch. This triggers a failed deployment attempt even though there is no merge happening. The change to `if: github.event_name == 'push'` should fix this, but that will not be reflected in the tests for this PR.
> Change condition for deploying docs

- config.defaults.yaml
- tools/featureGeneration/external_xmatch.py
- tools/generate_features.py
This PR adds external catalog crossmatches via cone search to the feature generation script. It adds a new section of the config file to specify which external features to get, then passes that info to `tools/featureGeneration/external_xmatch.py` which runs batch queries. The external features are incorporated into the existing set produced by `generate_features.py`.
> Add cone search queries for external catalog features

- .gitmodules
This PR pins the [scope-phenomenology](https://github.com/bfhealy/scope-phenomenology) repo, which contains the SCoPe Phenomenological Taxonomy used on Fritz. This removes the need to clone the repo separately from scope.
> Pin scope-phenomenology

- .github/workflows/docs.yml
This PR modifies the `docs` workflow to only attempt documentation deployment for pushes to the ZTF-owned scope repo (this one).
This should change nothing about actions behavior in this repo, but it should fix failing tests when pushing to forked repos and protect the docs from unintended deployments.
> Only deploy docs if merging to ZTF-owned scope repo

- .requirements/doc.txt
- config.defaults.yaml
- scope.py
- tools/generate_features.py
This PR allows users to generate cesium features in addition to the default scope/ztfperiodic features. The config file now contains the full list of available cesium features, and uncommented features will be generated if `-doCesium` is set in `generate_features.py`. 
Some overlapping features between scope/cesium and all periodic features are commented by default - the latter group because it requires an additional Lomb-Scargle analysis. Going forward we could modify cesium to accept a period from our existing analysis and compute Fourier features based on that value.
> Add option to generate cesium features

- tools/generate_features.py
- tools/generate_features_job_submission.py
- tools/generate_features_slurm.py
This PR adds code to generate slurm scripts to run scope feature generation in parallel on HPC resources. Changes include:
- `generate_features.py` (modified):
- Syntax update: all keywords now begin with `--` instead of `-`
- New check for cases where no light curves pass selection criteria
- New keywords have been added: `--doQuadrantFile`, `--quadrant_file` and `--quadrant_index` allow the field/ccd/quadrant to be specified using a generated `slurm.dat` file (described below)
- `generate_features_slurm.py` (new):
-  Optionally checks ZTF fields/ccd/quadrants for sources
- Maps each field/ccd/quadrant combo with sources to a quadrant index and saves a `slurm.dat` file
- Saves `slurm.sub` file with `SBATCH` commands and a call to `generate_features.py`. This call includes …
> Generate slurm scripts

- doc/usage.md
- scope/utils.py
- tools/get_features.py
- tools/inference.py
- tools/scope_download_classification.py
This PR adds the option to impute features when calling `get_features.py` using the strategies listed in the config. By using this new option, the user can both query features from Kowalski and impute missing features at the same time.
After imputation, the code drops rows that still have missing features if they have `include: True` in the config. That is, if there is no imputation strategy for a missing feature but that feature is included in training/inference, the row will be dropped to avoid downstream errors. For our current training set with ~180,000 light curves, only one source gets dropped.
This PR (along with #248) resolve #235 and #236 by minimizing the amount of imputation performed before training and inference.
> Impute features when using get_features.py

- .github/workflows/docs.yml
This PR attempts to fix docs deployment upon push, which seems to not have occurred since last week despite passing tests. This is likely due to the updated version of `JamesIves/github-pages-deploy-action` from `v3` to `v4`. There is a log warning at the beginning of the `Deploy docs` step stating:
`Warning: Unexpected input(s) 'REPOSITORY_NAME', 'SINGLE_COMMIT', 'SSH', valid inputs are ['ssh-key', 'token', 'branch', 'folder', 'target-folder', 'commit-message', 'clean', 'clean-exclude', 'dry-run', 'force', 'git-config-name', 'git-config-email', 'repository-name', 'tag', 'single-commit', 'silent']`
Thus, this PR changes the existing input names to those on the list of valid inputs.
> Update inputs for doc deploy workflow

- .gitmodules
This PR changes scope's submodule links from ssh to https. This is to avoid ssh-related errors when cloning scope to an HPC cluster.
> Change submodule links to https

- tools/get_quad_ids.py
This PR adds the `get_coords` flag seen in other functions in `get_quad_ids.py` to `get_cone_ids()`. Even though the ra and dec must be provided for this function, there are use cases which are facilitated by returning the `radec_geojson` coordinates in addition to the ZTF id.
> Add option to return geojson coordinates in cone search

- tools/featureGeneration/periodsearch.py
This PR modifies the behavior of `periodsearch.py` to issue a warning instead of raising an error when a source's period significance is `nan`. The error is occasionally raised for the `EAOV` algorithm in `periodfind`. While this change is not a permanent solution, it allows the feature generation script for a field/ccd/quad to continue.
We could additionally yield a `nan` period for sources where the AOV significance is `nan` - our downstream `lcstats.py` code should be able to handle that by returning `nan` for the Fourier features dependent on that period. Currently a finite period is returned even when the significance is `nan`.
> Replace periodsearch error with warning when significance is nan

- tools/generate_features_job_submission.py
- tools/generate_features_slurm.py
This PR adds the ability for generated slurm scripts to run multiple feature generation jobs in parallel HPC instances using `sbatch`. This new functionality is in addition to the existing approach of running each job in a single interactive instance.
Also, the `period_algorithm` argument in `generate_features_slurm.py` has been removed; users can instead use the config file to specify which algorithms to run.
> Submit feature generation jobs in parallel

- tools/featureGeneration/pyaov/build.sh
This PR revises the build script for pyaov to be compatible with the basic installation of scope dependencies (f2py is included with numpy).
> Revise build.sh for pyaov

- scope.py
- tools/generate_features.py
This PR allows the user to specify a new keyword to easily run `scope.py test` on a GPU (run `./scope.py test --doGPU`).
> Make GPU testing easier with new keyword

- tools/generate_features.py
- tools/generate_features_slurm.py
This PR modifies period finding to run in batches (default size 1000 light curves). Quadrants with many sources were raising obscure CUDA errors on Expanse when running all light curves at once, and these errors were not present for quadrants with fewer sources.
> Find periods in batches

- scope.py
- scope/utils.py
- tools/generate_features.py
- tools/get_quad_ids.py
This PR reduces the number of sources sent to `drop_close_bright_stars` by filtering by `min_n_lc_points` detections in `get_quad_ids.py`. It also adds the option to batch query Kowalski using the existing `Ncore` keyword.
> Filter light curve ids by N detections and batch query Kowalski

- scope/fritz.py
- tools/featureGeneration/alertstats.py
- tools/featureGeneration/external_xmatch.py
- tools/generate_features.py
This PR enables parallelization of Kowalski queries for ZTF light curves, alert stats and external catalogs.
> Parallelize Kowalski queries

- scope/utils.py
- tools/generate_features.py
This PR sorts each light curve to be monotonically increasing in time before generating features. Multiple feature generation algorithms, including `removeHighCadence()` and `compute_dmdt()`, rely on this sorting to produce results consistent with previous generated features.
> Sort light curves to be monotonically increasing in time

- tools/generate_features.py
- tools/get_quad_ids.py
This PR reduces the amount of time the feature generation script takes to query/identify nearby sources in Gaia that are too close to ZTF sources. Only one Gaia cone search is performed across the entire quadrant (as defined by the most extreme coordinates among sources on the list + a default 300 arcsec cushion).  In addition, a ~10x performance increase is realized by using `astropy.coordinates.angular_separation()` instead of `SkyCoord.separation()` to compute angular separations. This requires that latitudes/longitudes be calculated before looping over ZTF sources.
For the most crowded field among the 20 test fields (488), the entire process now runs in ~4 min, improving from a time of multiple hours. Closes #308
> Streamline query/analysis of nearby sources in Gaia

- tools/generate_features.py
For multi-core feature generation, this PR decreases the size limit for light curve queries until it is small enough to run batch  queries. Otherwise, the default `query_size_limit` of 10000 sources may be greater than the number of light curves to query.
> Ensure light curves are queried in batches

- config.defaults.yaml
- doc/field_guide.md
- doc/field_guide__bogus.md
- doc/field_guide__cepheid.md
- doc/field_guide__flaring.md
- doc/field_guide__periodic.md
- doc/field_guide__variable.md
This PR adds a field guide section with examples of bogus variability (specifically apparent flaring sources). It also updates the label abbreviations for other field guide sections (e.g. for `periodic`, the abbreviation is `pnp`).
> Add bogus field guide, update label abbreviations

- config.defaults.yaml
- tools/generate_features_job_submission.py
This PR enables feature generation on user-specified lists of fields, supplementing the default behavior that randomly selects quadrants from all available fields.
A fix is included that removes the code's ability to call feature generation on the same quadrant multiple times. This is unlikely early in the process but becomes more probable as the number of remaining quadrants decreases. The code also now terminates its loop of feature generation calls before performing any duplication at the very end of the process. When the number of available instances equals the number remaining jobs to be done, the code will stop looping after it submits these last jobs. 
There remains the possibility that a dwindling HPC allocation will hinder this code, since slurm will refuse jobs that request more …
> Generate features for fields specified in config

- config.defaults.yaml
- tools/generate_features_slurm.py
This PR sets the newly available `ZTF_sources_20230309` collection on `melman` as the default sources catalog in the config file. A typo in an argparse description is also fixed.
> Set ZTF DR16 as default sources catalog

- doc/usage.md
- tools/generate_features.py
- tools/generate_features_slurm.py
This PR replaces the `--doLongPeriod` flag with `--doScaleMinPeriod` and changes its behavior, from enforcing a fixed range of periods to scaling the minimum period (and thus maximum frequency) based on the cadence set by `min_cadence_minutes`. 
If `--doScaleMinPeriod` is set and `min_cadence_minutes` = $cadence$, the maximum frequency passed to period finding (modulo units) will be $1 / (2 * cadence)$, or the Nyquist frequency for that cadence.
> Add option to scale min period/max frequency for period finding

- scope.py
- tools/generate_features.py
This PR uses the changes made in #346 to speed up `scope.py test`. There are now fewer frequencies for the L-S periodogram algorithm to analyze. In addition, the removal of terrestrial frequencies is now tested.
> Speed up scope.py test by scaling min period

- config.defaults.yaml
- tools/generate_features.py
This PR adds (and in some cases, re-implements) functionality to `generate_features.py` to generate features for ZTF light curves with IDs from a config-specified file. A new `--doSpecificIDs` flag is added to the script to trigger the workflow.
The older query-by-ID approach (removed in #322) is employed to identify sources too close to bright stars in Gaia EDR3. As a solution to avoid wasting time on HPC resources, the script can now save the output from this query/analysis and then skip that step in subsequent runs (set `--skipCloseSources`). The faster approach is still used when generating features for a given field/cdd/quadrant.
This code will be especially useful for generating up-to-date features for our training set and testing period-finding algorithms.
> Enable feature generation for user-specified sources

- config.defaults.yaml
- scope.py
- scope/xgb.py
- tools/inference.py
This PR adds a hyperparameter cross-validation grid search to XGBoost, with the range of each grid customizable in the config file. The optimal parameters are saved/loaded from a new .params file that accompanies the saved model. The `load_config()` method has been tested, and it successfully loads the parameters and associates them with an instantiated model. 
As in the original jupyter notebook running this code, the grid search begins with the `max_depth` and `min_child_weights` parameters and continues with `subsample` and `colsample_bytree`, then `eta`, then one more round of `max_depth` and `min_child_weights`.
> Add hyperparameter grid search to XGBoost training

- config.defaults.yaml
- tools/generate_features.py
This PR fixes the failing scope test suite by switching hardcoded `melman` references to `gloria`. This will need to be undone once `melman` is available in order for feature generation to run on the correct catalog. Once the latest version of `penquins` is released, the code will no longer need these references to specific instances (see #330).
> Fix failing test suite by removing melman references

- doc/usage.md
- tools/scope_download_classification.py
- tools/scope_manage_annotation.py
- tools/scope_upload_classification.py
Our Fritz download/upload/annotation scripts currently take command line arguments with one hyphen, e.g. `-file`. For the sake of consistency with our other scripts that take arguments (as well as Unix standards), this PR adds a second hyphen to all arguments longer than one character in these scripts. The documentation is updated accordingly.
> Add additional hyphen to arguments in download/upload/annot scripts

- tools/scope_download_classification.py
This PR modifies `scope_download_classification.py` to enable the expansion of the current training set by downloading active learning classifications. If `--update_training_set` is set, the code will check whether a classification's 'net votes' (the difference between number of upvotes and downvotes) is ≥ the user-specified threshold (default 1). Each classification satisfying this criterion will be included in the file produced by running the script.
Although the active learning sample is intended to be selected from sources not already in the training set, the code searches for any overlap using ZTF light curve IDs. Light curves duplicated between the training and AL samples receive updated classifications from the latter, and the original entry in the file is removed. The code places …
> Add ability to download active learning classifications, merge with training set

- tools/featureGeneration/lcstats.py
This PR renames `relphi5` to `relphi4` in two `lcstats` functions to reduce confusion.
> Rename relphi5 to relphi4 in calc_stats and calc_fourier_stats

- tools/XGB_AL_mapper.json
- tools/scope_upload_classification.py
This PR adds a Fritz taxonomy mapper file for labels from XGB and updates the DNN mapper to cover all current binary classifiers.
> Add XGB taxonomy mapper, modify DNN mapper

- tools/generate_features_slurm.py
This PR allows a json file containing Kowalski catalog completeness results to be saved.
> Allow catalog completeness results to be saved

- tools/generate_features_slurm.py
This PR switches a `find` Kowalski query in `check_quads_for_sources` to `count_documents`, which offers ~10x time savings over querying individual IDs.
> Switch find query to count_documents in check_quads_for_sources()

- tools/featureGeneration/external_xmatch.py
This PR attempts to fix a bug where generated feature files contain unneeded coordinate columns associated with external catalogs (e.g. `PS1_DR1__coordinates.radec_geojson`). This happens when generating features on enough sources to require at least two iterations over the loop in `external_xmatch.py`. The fix moves the code associated with defining the desired external features outside the loop. It will be merged after I confirm it works as intended on the full list of training sources.
> Move external catalog feature projections outside loop

- tools/generate_features_slurm.py
This PR converts dictionary keys in `check_quads_for_sources` to `str` to avoid a `json.dump` error when saving.
> Fix json.dump bug in catalog completeness code

- tools/generate_features_slurm.py
- tools/get_quad_ids.py
This PR adds a `minobs` argument to `check_quads_for_sources`. Setting this argument to the minimum number of light curve points enforced in scope (currently 50) will help provide more accurate feature generation runtime estimates. This is because the longest-running part of feature generation, the period finding, only runs on sources having ≥ `minobs` points. 
Also in this PR, a `$gt` is changed to `$gte$` in `get_quad_ids.py` to be consistent with the stated strategy of using light curves having N or more points.
> Add minobs filter to catalog completeness code

- tools/inference.py
This PR adds ZTF field/ccd/quad/filter fields to each row in the file produced by `inference.py`. Previous classification catalogs have lacked this information, but it could be useful when querying new classification catalogs in the future.
> Add field/ccd/quad/filter info to inference results

- scope.py
- tools/inference.py
This PR changes the default file format for inference results to parquet. This change, combined with the explicit conversion of integer fields to pandas `Int64` type, ensures that Kowalski ingests these fields as integers rather than floats.
> Save inference results as parquet instead of hdf5

- tools/generate_features.py
Currently in `generate_features.py`, the ZTF ID for each source is stored as the index column. This PR renames that column to `_id` (to interface smoothly with kowalski/mongoDB) and then resets the index so the `_id` column can be accessed during ingestion.
> Rename generated features index to '_id', reset index

- scope.py
This PR adapts `scope.py select_al_sample` to run on GCN sources if `fields` is set to `'specific_ids'`. The method is renamed `select_fritz_sample` to reflect its broader applicability.
The output is a file ready for `scope_upload_classification.py` containing the original obj_ids from Fritz and any classifications above the desired threshold.
By default:
- Classifications are based on light curves within 2 arcsec of each GCN source's coordinates
- Light curves must have at least 50 epochs to receive generated features -> classifications
- If multiple light curves exist for a source, their classification probabilities are combined via the mean. Median and max are also supported.
> Adapt active learning code to consolidate GCN source classifications

- tools/generate_features.py
- tools/scope_download_gcn_sources.py
This PR makes updates to feature generation and GCN source querying to make the workflow run more smoothly. Primarily:
- Bugfix: the page-by-page query was missing `localizationDateobs`, `startDate` and `endDate`.
- A parquet file is now generated by `scope_download_gcn_sources.py` to be used as the primary input to the feature generation script. `generate_features.py` handles this file smoothly and passes on the identifiers from Fritz if they are available.
> Gcn workflow updates

- tools/generate_features_job_submission.py
#392 did not adequately fix the slurm job submission bug. This PR solves the issue by restoring some of the script's original functionality but introducing a `new_max_instances` variable that defines how many instances can be run at once based on how many jobs remain. This change keeps things running smoothly regardless of whether more or fewer jobs remain than `args.max_instances`.
> Address remaining job submission bug

- tools/generate_features_job_submission.py
- tools/train_algorithm_job_submission.py
This PR builds on #409, adapting the approach of distinguishing between running and completed jobs in `generate_features_job_submission.py`. 
Unneeded code is also removed from `train_algortihm_job_submission.py`, and a keyword to specify the model's group name (independent of the training script) is added.
> Adapt new job submission approach for feature generation

- tools/generate_features_job_submission.py
- tools/generate_features_slurm.py
This PR adds a default 1-minute interval between feature generation job submissions. The intent of this interval is to slightly stagger kowalski queries to avoid the following errors: 
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='melman.caltech.edu', port=443): Max retries exceeded with url: /api/queries (Caused by ResponseError('too many 502 error responses'))
```
```
requests.exceptions.RetryError: HTTPSConnectionPool(host='melman.caltech.edu', port=443): Max retries exceeded with url: /api/queries (Caused by ResponseError('too many 502 error responses'))
```
> Add interval between feature generation job submissions

- tools/generate_features_job_submission.py
In `generate_features_job_submission.py`, this PR redefines the number of jobs to queue based on `nchoice` instead of `njobs`. This avoids an error in the submission script once all jobs have been queued.
> Define amount of jobs to queue based on nchoice

- config.defaults.yaml
- scope.py
- tools/inference.py
- tools/run_inference_job_submission.py
- tools/run_inference_slurm.py
This PR adds code to run inference jobs on Expanse following the pattern of feature generation and training. A new section of the config file specifies the fields on which to run inference, and the other details are specified via `run_inference_slurm.py`. After running `slurm_submission.sub`, `run_inference_job_submission.py` checks for parquet files in each field of the predictions directory, queuing inference jobs for fields lacking results.
> Add support for inference slurm jobs

- scope.py
- scope/fritz.py
This PR fixes the query in `get_lightcurves_via_coords` to work with penquins 2.3.1. The PR also sets the default source catalog using the config file rather than selecting the last catalog name in a list. A call to `get_lightcurves_via_coords` is added to the tests.
> Fix get_lightcurves_via_coords for new penquins, add to tests

- combine_preds.py
- scope.py
- tools/combine_preds.py
Changes to `inference.py` have rendered `combine_preds.py` obsolete in its current form. This PR overhauls `combine_preds.py` to serve the new purpose of combining DNN and XGB prediction columns into one parquet file per field. This will facilitate a single-step ingestion of DNN/XGB predictions to Kowalski, which is important since Kowalski code does not currently support update existing entries with new fields.
> Overhaul combine_preds to facilitate Kowalski ingestion

- tools/generate_features.py
This PR allows the filepath for a source list to be specified in calls to `generate_features.py`, rather than only in the config file. This will be useful for running cron jobs on transient candidates.
> Allow feature generation sources filepath to be specified in calls to script

- tools/train_algorithm_slurm.py
This PR makes a copy of training script line info so the code detects the algorithm kwarg. Previously it was removed owing to list mutability, so the algorithm would default to 'dnn' even when 'xgb' was specified.
> Fix missing algorithm kwarg in slurm training script

- gcn_cronjob.py
- scope.py
- tools/combine_preds.py
- tools/fritz_mapper.json
- tools/inference.py
- tools/scope_download_gcn_sources.py
- tools/scope_upload_classification.py
This PR adds a script (`gcn_cronjob.py`) that automatically classifies light curves within 0.5 arcsec (by default) of candidates for GCN events. The script queries all GCN events within the last 14 days, identifies any new sources, runs feature generation on Expanse, pulls those results and runs inference locally, consolidates predictions, and uploads DNN/XGB classifications above a mean probability threshold of 0.7. A metadata file for each event lists sources and their classifications passing the threshold.
This script can be run as a cron job, e.g. on the hour:
```
0 * * * * ~/miniforge3/envs/scope-env/bin/python ~/scope/gcn_cronjob.py > ~/scope/log_gcn_cronjob.txt 2>&1
```
A future PR will allow light curve plots associated with the classifications to be posted as comments.
> Add script to automatically classify sources near GCN candidates

- gcn_cronjob.py
- tools/scope_upload_classification.py
This PR fixes `gcn_cronjob.py` bugs that raised errors for single-dateobs querying and uploading empty classification lists.
> Fix bugs for single dateobs, empty classification list

- gcn_cronjob.py
- scope.py
The cron environment does not have access to the same paths and environment variables as a login shell. This PR updates `gcn_cronjob.py` to run successfully given these differences. Most notably, the path to the scope environment's python installation (with all required packages installed) can now be specified. Some background info is added as comments here, with more documentation planned for a future PR.
> Fix cronjob issues specific to running in cron environment

- scope/nn.py
- scope/utils.py
- scope/xgb.py
Training stats are currently included in output plots, but there is no text file to read for easy access. This PR saves a json file containing a model's accuracy, precision, recall, f1 score, and area under ROC curve for each of the train, val and test sets.
> Save training stats in json file

- gcn_cronjob.py
This PR updates the default `daysAgo` argument in the GCN cronjob from 14 to 7 days, so the code will only consider events happening within the last 7 days. This adds consistency with another argument that determines how far forward to search for sources (`days_range`), which is already 7 days by default. This means that once the cron job runs once, GCN events happening prior to 7 days ago will not receive any new sources/classifications under the current defaults.
Making this change reduces the run time of each cron job and removes unnecessary calls to the Fritz API. Usually `daysAgo` and `days_range` should be the same, except for cases where the cron job hasn't run in a while. In those cases, `daysAgo` may be somewhat greater than `days_range`.
> Update default GCN cronjob daysAgo

- .github/workflows/test_no_kowalski.yml
- config.defaults.yaml
- scope.py
This PR adds a test workflow that does not require a Kowalski connection. It also removes balance hyperparameter values from the config defaults, since we currently train all classifiers on the full training set.
> Add test workflow without Kowalski connection

- doc/usage.md
- tools/scope_upload_classification.py
This PR allows scope to take advantage of impending changes to skyportal (see https://github.com/skyportal/skyportal/pull/4441) that distinguish between human and ML classifications. It will be merged once the skyportal changes are deployed to Fritz.
> Distinguish between human/ML classifications when uploading

- tools/inference.py
To facilitate running `inference.py` in a Jupiter notebook for the ZTF summer school, this PR changes how the code determines the `type` of the `field` variable. This is necessary since the `os.system` commands in the notebook always provide the field as a string.
> Change how inference.py determines field type

- scope.py
This PR uses the new `self.base_path` attribute in `scope.py` in more places where pathlib.Path(...) was previously used.
> Use self.base_path in scope.py

- doc/index.rst
- doc/scanner.md
This PR adds the new scanner guide to the documentation index so it can be reached more easily.
> Add scanner guide to docs index

- doc/usage.md
- gcn_cronjob.py
- scope/fritz.py
- tools/scope_upload_classification.py
This PR adds the ability for `scope_upload_classification.py` to generate ZTF photometry plots and post these plots as comments/attachments on Fritz. It is important not to post this photometry to the source itself when that source is a transient candidate, or the time of first detection will be changed. 
Example photometry plot:
Example comment text and attachment on SkyPortal:
> Post ZTF photometry plots as comments when uploading classifications

- gcn_cronjob.py
This PR adds phase-folded light curves to the plots posted as comments by `gcn_cronjob.py`.
> Add phase-folding argument to gcn_cronjob.py classification uploads

- gcn_cronjob.py
This PR prevents the `--ignore_checkpoint` flag in `gcn_cronjob.py` from adding duplicate entries of ZTF candidate ids to the checkpoint list.
> Prevent --ignore_checkpoint from duplicating checkpoint entries in gcn_cronjob.py

- doc/scanner.md
This PR adds a line to the scanner documentation describing the light curve plots that are posted to Fritz when `gcn_cronjob.py` runs.
> Add light curve plot description to Fritz scanner guide

- gcn_cronjob.py
This PR increases the default time interval to refresh the GCN cronjob checkpoint list from 30 to 180 days.
> Increase cronjob checkpoint refresh to 180 days

- doc/usage.md
This PR adds tables to the Usage docs defining the phenomenological and ontological features Scope classifiers currently use.
> Add selected feature definition tables to usage.md

- scope.py
This PR adds a method to `scope.py` that finds all classifier performance stats and copies them to a new directory so they are more easily accessible.
> Add method to find and copy classifier stats to new directory

- .requirements/doc.txt
- scope.py
This PR adds code to save a plot of the DNN architecture using `tf.keras.utils.plot_model`. It also adds a `pydot` requirement needed for this code to work.
> Plot DNN architecture during training

- doc/usage.md
- tools/get_features.py
This PR refactors `get_features.py` to use `argparse` inputs consistent with other SCoPe code (e.g. `get_quad_ids.py`). Documentation is updated accordingly.
> Refactor get_features.py to use consistent argparse inputs

- scope.py
- scope/utils.py
- scope/xgb.py
This PR changes the behavior of the `balance` hyperparameter so that only the training set is modified. The validation and test sets are left unchanged regardless of the desired balance to ensure that stats like precision and recall can be compared to each other across all training runs. 
Additionally, the `weight_per_class` parameter can now be used during XGB training by setting the `scale_pos_weight` parameter under the hood.
> Only apply balancing to training set, leaving val and test sets unchanged

- scope.py
- scope/nn.py
- scope/utils.py
- scope/xgb.py
This PR makes updates to the default confusion matrix and feature importance plots:
- Confusion matrices show normalized values by default and do not include score annotations
- Feature importance plots have shortened titles and do not include the F score at the end of each bar
Examples below:
[pnp.20230831_202314_cm.pdf](https://github.com/ZwickyTransientFacility/scope/files/12490067/pnp.20230831_202314_cm.pdf)
[pnp.20230831_202314_impvars.pdf](https://github.com/ZwickyTransientFacility/scope/files/12490068/pnp.20230831_202314_impvars.pdf)
> Update confusion matrix and feature importance plots

- scope/fritz.py
This PR reduces api calls to Fritz when posting new sources. Specifically, the code checks for exiting period annotations before sending a POST request, and it queries current instruments once rather than on a per-source basis.
Also, two rarely-used functions are moved to the bottom of the file.
> Reduce annotation/instrument api calls when posting sources

- doc/usage.md
- scope/fritz.py
- tools/scope_upload_classification.py
This PR moves the instrument API request from `fritz.py` to `scope_upload_classification.py`. This avoids the automatic running of this request whenever code from `fritz.py` is imported, while allowing a new `--instrument_name` argument to be passed to `scope_upload_classification.py`.
> Move Fritz instrument_id request to upload script

- tools/generate_features.py
This PR fixes a bug in feature generation in which a KeyError could be raised when calculating basic stats. The bug occurred because sources that generated a separate error during initial/cesium feature generation were not always removed from all relevant dictionaries.
> Fix feature generation KeyError bug

- config.defaults.yaml
- gcn_cronjob.py
- tools/generate_features.py
- tools/generate_features_job_submission.py
- tools/generate_features_slurm.py
- tools/inference.py
- tools/run_inference_job_submission.py
- tools/run_inference_slurm.py
SCoPe code typically references a single `BASE_DIR` that contains the code along with input and output data. This PR adds more flexibility by allowing users to specify a `path_to_features` in the config file other than the base SCoPe directory. If this path is given, the `BASE_DIR` variable will be redefined in feature generation code and results will be saved to the specified directory. This is useful for generating features on a cluster, where the code's installation directory may not be ideal for saving larger files. 
Additionally, this PR makes use of the existing `path_to_preds` config entry to allow inference results to be saved in a directory other than the base code directory. Further testing will be done on Expanse to ensure the path updates work as intended.
(See also #488)
> Allow more path customization for feature generation/inference

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/test_no_kowalski.yml
- .requirements/dev-M1.txt
- .requirements/dev.txt
- .requirements/doc.txt
- doc/developer.md
This PR standardizes the scope installation process across all platforms, removing `dev-M1.txt` and instead installing tensorflow with pip. The documentation is updated to reflect the new installation steps, and tests are now run using Python 3.11. 
(Resolves #347, resolves #494)
> Standardize installation across platforms

- .requirements/doc.txt
- doc/developer.md
This PR adds an h5py requirement to doc.txt, enabling all scope requirements to be installed using pip. This progresses toward the goal of #495.
> Add h5py to doc requirements

- config.defaults.yaml
- scope/fritz.py
This PR allows all light curves queried from Kowalski to be truncated at a config-specified MJD. Note that since timestamps on Kowalski are measured in HJD, for any given source there is a coordinate-dependent discrepancy of ±8.3 mins between the two time units due to light travel time between the Earth/Sun. This should not be a major issue given that we later enforce a requirement that light curve points be spaced by no less than 30 minutes.
> Add configurable time cutoff to mongoDB light curve query

- doc/usage.md
- scope/fritz.py
- tools/generate_features.py
This PR allows `--max_timestamp_hjd` to be specified as an argument in `generate_features.py`, bringing it in line with other arguments that can be specified both in `config.yaml` and the feature generation script.
> Add max_timestamp_hjd as argument in generate_features.py

- tools/generate_features_slurm.py
This PR ensures that a completeness file exists before attempting to load it, avoiding a potential error when generating a new file.
> Check for completeness file before loading

- tools/analyze_logs.py
This PR adds a new tools script to read slurm log files from feature generation jobs, pairing the job runtimes with the number of initial sources. When given a text file of the form `"job id,runtime"` from the automated slurm emails, e.g.
```
"25401362,16:05:28"
"25401338,11:31:10"
"25401382,1-20:20:16"
...
```
this code will produce a json file output that contains information relevant for predicting the runtime of future jobs, given the number of initial sources:
```
{"25401362": {"n_sources_start": 25190, "n_sources_end": 24443, "runtime_seconds": 57928.0, "seconds_per_source_start": 2.2996427153632393}, "25401338": {"n_sources_start": 27633, "n_sources_end": 26724, "runtime_seconds": 41470.0, "seconds_per_source_start": 1.5007418666087649}, "25401382": {"n_sources_start": 19141, …
```
> Add script to analyze feature generation log files

- tools/generate_features.py
This PR adds the total runtime to the outputs logged during feature generation. This will simplify future efforts to compare runtimes and the number of initial sources per quadrant (eliminating the present need to parse slurm email subject lines for runtimes).
> Add runtime to feature generation logs

- tools/analyze_logs.py
This PR refactors `tools/analyze_logs.py` to use the feature generation runtime in the recently added last line of slurm log entries (see #525). The code no longer requires a separate text file with job IDs and runtimes from slurm emails.
> Refactor analyze_logs to use new runtime line

- tools/inference.py
This PR excludes invalid files in feature generation output (e.g. `.running` files) from inference, avoiding an `ArrowInvalid` error.
> Exclude invalid files from inference dataset

- tools/generate_features_job_submission.py
- tools/generate_features_slurm.py
This PR modifies `tools/generate_features_job_submission.py` to count running jobs using `squeue` before submitting additional feature generation jobs. This allows each 48-hour run of the submission script to be run back-to-back with the next run (e.g. as a cron job), since the new instance of the script will have access to the current active job count.
The new code also makes more efficient use of real time by recognizing any failed jobs and queuing a new jobs to take their place. Previously any failures would restrict the max number of instances available for new jobs queued from the same script run. The user will still need to run another iteration of the script to re-run any failed jobs.
> Check running jobs before feature generation job submission

- config.defaults.yaml
This PR updates the config defaults with the new DR20 catalog on melman (`ZTF_sources_20240117`) and adds the default HJD cutoff (2459951.5) limiting light curves from this catalog to the DR16 timespan.
> Update config defaults with DR20 catalog, DR16 HJD cutoff

- config.defaults.yaml
This PR updates the config defaults to reflect Scope III paper revisions (specifically adding Gaia EDR3 parallax error as an ontological feature with median imputation).
> Update config defaults with changes from paper revision

- .github/workflows/publish-to-pypi.yml
This PR adds a workflow to publish scope releases to PyPI using poetry. The workflow runs when a commit is tagged with `v*.*.*`. See https://github.com/marketplace/actions/publish-python-poetry-package for more info.
Note: tests will continue to fail until #514 is merged after some additional testing/debugging.
> Add PyPI publishing workflow

- .github/workflows/publish-to-pypi.yml
This PR specifies the python version as 3.11 in the pypi publication workflow.
> Specify python version in pypi workflow

- tools/combine_preds.py
This PR skips the `combine-preds` workflow for fields that already have a file in `preds_dnn_xgb`.
> Skip combine-preds for fields with existing file

- tools/combine_preds.py
This PR modifies `combine_preds.py` to write a json file containing a list of all available fields. This list will be added to the Zenodo record to describe which fields can be downloaded.
> Write json file containing list of available fields

- doc/developer.md
This PR adds instructions on creating a new PyPI release of `scope-ml` to the developer docs.
> Add pypi release to developer docs

- config.defaults.yaml
- tools/combine_preds.py
- tools/generate_features_job_submission.py
- tools/run_inference_job_submission.py
This PR allows a user to list fields to exclude from feature generation/inference in the config file (under fields_to_exclude). This prevents duplication of effort even if completed field files are not present locally.
> Allow user to specify fields to exclude from feat gen/inference

- scope/utils.py
This PR adds a util to save a file containing field-by-field light curve counts given a catalog_completeness file (see `tools.generate_features_slurm.check_quads_for_sources`) as input.
> Add util to save LC count by field given catalog_completeness file

- doc/index.rst
- doc/zenodo.md
This PR adds a docs page describing zenodo data releases and how to prepare/publish new versions.
> Add zenodo release documentation

- pyproject.toml
- requirements.txt
This PR adds a cython requirement to make `periodfind` installations easier on cluster resources.
> Add cython requirement for periodfind

- tools/get_features.py
This PR fixes a bug in which the wrong path is used by pip-installed scope when testing `get_features.py`.
> Fix path bug in get_features.py

- tools/combine_preds_slurm.py
- tools/generate_features_slurm.py
- tools/run_inference_slurm.py
- tools/train_algorithm_slurm.py
This PR updates all slurm script generators to include specific lines for NSCA Delta. Note that while scope feature generation runs on Delta GPUs, at the moment it appears to take ~2x as long to complete compared to Expanse. This seems too slow for A100s but also too fast to be avoiding the GPUs altogether.
> Update slurm script generators with NSCA Delta specifics

- tools/combine_preds.py
This PR fixes a bug that mixed int and str types in the fields lists of `combine_preds.py`. The saved list now contains integer fields numbers instead of strings, but the code converts back to `"field_N"` format when checking existing files saved in that format.
> Fix dtype bug in combine-preds field lists

- scope/scope_class.py
This PR adds a separate `--plot-model` arg to training in an attempt to avoid Windows-related errors with `tensorflow.keras.utils.plot_model`.
> Add separate plot_model arg to training
